import os
import numpy as np
import matplotlib.pyplot as plt


def compare_benchmarks(
    benchmark_dir_1,
    benchmark_dir_2,
    label_1="Policy 1",
    label_2="Policy 2",
    out_dir=None,
    show=True
):
    """
    Compare two benchmark folders generated by the benchmark script.

    Expected structure:
        benchmark_dir/
            aggregated.npy

    Parameters
    ----------
    benchmark_dir_1 : str
    benchmark_dir_2 : str

    label_1 : str
    label_2 : str

    out_dir : str or None
        If provided, saves figures there.

    show : bool
        If True, displays plots.
    """

    # =========================================================
    # Load aggregated benchmark files
    # =========================================================

    agg1_path = os.path.join(benchmark_dir_1, "aggregated.npy")
    agg2_path = os.path.join(benchmark_dir_2, "aggregated.npy")

    agg1 = np.load(agg1_path, allow_pickle=True).item()
    agg2 = np.load(agg2_path, allow_pickle=True).item()

    # =========================================================
    # Create output directory
    # =========================================================

    if out_dir is not None:
        os.makedirs(out_dir, exist_ok=True)

    # =========================================================
    # CoT comparison
    # =========================================================

    plt.figure(figsize=(6, 4))

    plt.errorbar(
        agg1["vel"],
        agg1["cot_mean"],
        yerr=agg1["cot_std"],
        marker="o",
        capsize=4,
        label=label_1
    )

    plt.errorbar(
        agg2["vel"],
        agg2["cot_mean"],
        yerr=agg2["cot_std"],
        marker="o",
        capsize=4,
        label=label_2
    )

    plt.xlabel("Velocity (m/s)")
    plt.ylabel("Cost of Transport (CoT)")
    plt.title("CoT Comparison")
    plt.grid(True)
    plt.legend()

    if out_dir is not None:
        plt.savefig(
            os.path.join(out_dir, "cot_comparison.png"),
            dpi=300,
            bbox_inches="tight"
        )

    # =========================================================
    # RMSE comparison
    # =========================================================

    plt.figure(figsize=(6, 4))

    plt.errorbar(
        agg1["vel"],
        agg1["rmse_mean"],
        yerr=agg1["rmse_std"],
        marker="o",
        capsize=4,
        label=label_1
    )

    plt.errorbar(
        agg2["vel"],
        agg2["rmse_mean"],
        yerr=agg2["rmse_std"],
        marker="o",
        capsize=4,
        label=label_2
    )

    plt.xlabel("Velocity (m/s)")
    plt.ylabel("Velocity RMSE")
    plt.title("Tracking Error Comparison")
    plt.grid(True)
    plt.legend()

    if out_dir is not None:
        plt.savefig(
            os.path.join(out_dir, "rmse_comparison.png"),
            dpi=300,
            bbox_inches="tight"
        )

    # =========================================================
    # Optional Pareto plot
    # =========================================================

    plt.figure(figsize=(6, 5))

    plt.plot(
        agg1["rmse_mean"],
        agg1["cot_mean"],
        marker="o",
        label=label_1
    )

    plt.plot(
        agg2["rmse_mean"],
        agg2["cot_mean"],
        marker="o",
        label=label_2
    )

    for i, v in enumerate(agg1["vel"]):
        plt.annotate(f"{v:.2f}", (agg1["rmse_mean"][i], agg1["cot_mean"][i]))

    for i, v in enumerate(agg2["vel"]):
        plt.annotate(f"{v:.2f}", (agg2["rmse_mean"][i], agg2["cot_mean"][i]))

    plt.xlabel("Velocity RMSE")
    plt.ylabel("Cost of Transport (CoT)")
    plt.title("Efficiency vs Tracking Tradeoff")
    plt.grid(True)
    plt.legend()

    if out_dir is not None:
        plt.savefig(
            os.path.join(out_dir, "pareto_comparison.png"),
            dpi=300,
            bbox_inches="tight"
        )

    # =========================================================
    # Show
    # =========================================================

    if show:
        plt.show()

    else:
        plt.close("all")

def main():
    path1= "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/1500_plane_symmetry/benchmark" #rnd
    path2= "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_snn/1500_plane_symmetry_spike/benchmark" #snn

    compare_benchmarks(
    path1,
    path2,
    label_1="rnd",
    label_2="snn",
    out_dir=None,
    show=True)
    
if __name__ == "__main__":
    main()