import os
import numpy as np
import matplotlib.pyplot as plt


def compare_benchmarks(
    benchmark_dirs,
    labels=None,
    out_dir=None,
    show=True
):
    """
    Compare multiple benchmark folders generated by the benchmark script.
    """

    # =========================================================
    # Input checks
    # =========================================================

    n = len(benchmark_dirs)

    if labels is None:
        labels = [f"Policy {i+1}" for i in range(n)]

    assert len(labels) == n, "labels and benchmark_dirs must have same length"

    # =========================================================
    # Load all aggregated files
    # =========================================================

    aggregations = []

    for path in benchmark_dirs:

        agg_path = os.path.join(path, "aggregated.npy")

        if not os.path.exists(agg_path):
            raise FileNotFoundError(f"Missing aggregated.npy in:\n{path}")

        agg = np.load(agg_path, allow_pickle=True).item()

        aggregations.append(agg)

    # =========================================================
    # Create output directory
    # =========================================================

    if out_dir is not None:
        os.makedirs(out_dir, exist_ok=True)

    # =========================================================
    # Colormap
    # =========================================================

    cmap = plt.get_cmap("tab10")
    colors = [cmap(i % 10) for i in range(n)]

    # =========================================================
    # CoT comparison
    # =========================================================

    plt.figure(figsize=(7, 5))

    for agg, label, color in zip(aggregations, labels, colors):

        plt.errorbar(
            agg["vel"],
            agg["cot_mean"],
            yerr=agg["cot_std"],
            marker="o",
            capsize=4,
            linewidth=2,
            color=color,
            label=label
        )

    plt.xlabel("Velocity (m/s)")
    plt.ylabel("Cost of Transport (CoT)")
    plt.title("CoT Comparison")
    plt.grid(True)

    # legend = policy ↔ color
    plt.legend(title="Policies")

    if out_dir is not None:
        plt.savefig(
            os.path.join(out_dir, "cot_comparison.png"),
            dpi=300,
            bbox_inches="tight"
        )

    # =========================================================
    # RMSE comparison
    # =========================================================

    plt.figure(figsize=(7, 5))

    for agg, label, color in zip(aggregations, labels, colors):

        plt.errorbar(
            agg["vel"],
            agg["rmse_mean"],
            yerr=agg["rmse_std"],
            marker="o",
            capsize=4,
            linewidth=2,
            color=color,
            label=label
        )

    plt.xlabel("Velocity (m/s)")
    plt.ylabel("Velocity RMSE")
    plt.title("Tracking Error Comparison")
    plt.grid(True)

    plt.legend(title="Policies")

    if out_dir is not None:
        plt.savefig(
            os.path.join(out_dir, "rmse_comparison.png"),
            dpi=300,
            bbox_inches="tight"
        )

    # =========================================================
    # Pareto plot
    # =========================================================

    plt.figure(figsize=(8, 6))

    for agg, label, color in zip(aggregations, labels, colors):

        plt.plot(
            agg["rmse_mean"],
            agg["cot_mean"],
            marker="o",
            linewidth=2,
            color=color,
            label=label
        )

        # velocity annotations
        for i, v in enumerate(agg["vel"]):

            plt.annotate(
                f"{v:.2f}",
                (agg["rmse_mean"][i], agg["cot_mean"][i]),
                fontsize=8,
                color=color
            )

    plt.xlabel("Velocity RMSE")
    plt.ylabel("Cost of Transport (CoT)")
    plt.title("Efficiency vs Tracking Tradeoff")
    plt.grid(True)

    plt.legend(title="Policies")

    if out_dir is not None:
        plt.savefig(
            os.path.join(out_dir, "pareto_comparison.png"),
            dpi=300,
            bbox_inches="tight"
        )

    # =========================================================
    # Show
    # =========================================================

    if show:
        plt.show()
    else:
        plt.close("all")


def main():

    benchmark_dirs = [

        "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/1500_plane_symmetry/benchmark",

        "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/1500_symmetry_0.0013/benchmark",

        "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_snn/1500_plane_symmetry_spike/benchmark",

        # add more here
    ]

    labels = [
        "rnd1",
        "rnd2",
        "snn",
    ]

    compare_benchmarks(
        benchmark_dirs,
        labels=labels,
        out_dir=None,
        show=True
    )


if __name__ == "__main__":
    main()