import os
import numpy as np
import matplotlib.pyplot as plt
from brokenaxes import brokenaxes

import os
import numpy as np
import pandas as pd


def create_reference_velocity_table(
    benchmark_dirs,
    labels,
    reference_velocity=1.0
):

    aggregations = []

    for path in benchmark_dirs:

        agg_path = os.path.join(path, "aggregated.npy")

        agg = np.load(
            agg_path,
            allow_pickle=True
        ).item()

        aggregations.append(agg)

    # ---------------------------
    # Find velocity index
    # ---------------------------

    vels = aggregations[0]["vel"]

    idx = np.argmin(np.abs(vels - reference_velocity))

    selected_vel = vels[idx]

    # ---------------------------
    # Baseline
    # ---------------------------

    baseline_cot = aggregations[0]["cot_mean"][idx]
    baseline_rmse = aggregations[0]["rmse_mean"][idx]

    rows = []

    for label, agg in zip(labels, aggregations):

        cot = agg["cot_mean"][idx]
        cot_std = agg["cot_std"][idx]

        rmse = agg["rmse_mean"][idx]
        rmse_std = agg["rmse_std"][idx]

        delta_cot = 100.0 * (cot - baseline_cot) / baseline_cot
        delta_rmse = 100.0 * (rmse - baseline_rmse) / baseline_rmse

        rows.append({
            "Model": label,
            "CoT": f"{cot:.3f} ± {cot_std:.3f}",
            "RMSE": f"{rmse:.3f} ± {rmse_std:.3f}",
            "ΔCoT (%)": f"{delta_cot:+.1f}",
            "ΔRMSE (%)": f"{delta_rmse:+.1f}"
        })

    df = pd.DataFrame(rows)


    return df

def compare_benchmarks(
    benchmark_dirs,
    labels=None,
    out_dir=None,
    show=True
):
    """
    Compare multiple benchmark folders generated by the benchmark script.
    """

    # =========================================================
    # Input checks
    # =========================================================

    n = len(benchmark_dirs)

    if labels is None:
        labels = [f"Policy {i+1}" for i in range(n)]

    assert len(labels) == n, "labels and benchmark_dirs must have same length"

    # =========================================================
    # Load all aggregated files
    # =========================================================

    aggregations = []

    for path in benchmark_dirs:

        agg_path = os.path.join(path, "aggregated.npy")

        if not os.path.exists(agg_path):
            raise FileNotFoundError(f"Missing aggregated.npy in:\n{path}")

        agg = np.load(agg_path, allow_pickle=True).item()

        aggregations.append(agg)

    # =========================================================
    # Create output directory
    # =========================================================

    if out_dir is not None:
        os.makedirs(out_dir, exist_ok=True)

    # =========================================================
    # Colormap
    # =========================================================

    cmap = plt.get_cmap("tab10")
    colors = [cmap(i % 10) for i in range(n)]

    # =========================================================
    # CoT comparison
    # =========================================================

    plt.figure(figsize=(10, 5))

    for agg, label, color in zip(aggregations, labels, colors):

        plt.errorbar(
            agg["vel"],
            agg["cot_mean"],
            yerr=agg["cot_std"],
            marker="o",
            capsize=4,
            linewidth=2,
            color=color,
            label=label
        )
    #plt.yscale("log")
    plt.ylim(bottom=0.28, top=.4)
    plt.xlabel("Velocity (m/s)")
    plt.ylabel("Cost of Transport (CoT)")
    plt.title("CoT Comparison")
    plt.grid(True)

    # legend = policy ↔ color
    plt.legend(title="Policies")

    if out_dir is not None:
        plt.savefig(
            os.path.join(out_dir, "cot_comparison.png"),
            dpi=300,
            bbox_inches="tight"
        )

    # =========================================================
    # RMSE comparison
    # =========================================================

    plt.figure(figsize=(10, 5))

    for agg, label, color in zip(aggregations, labels, colors):

        plt.errorbar(
            agg["vel"],
            agg["rmse_mean"],
            yerr=agg["rmse_std"],
            marker="o",
            capsize=4,
            linewidth=2,
            color=color,
            label=label
        )

    plt.ylim(bottom=0.0, top=0.4)
    plt.xlabel("Velocity (m/s)")
    plt.ylabel("Velocity RMSE")
    plt.title("Tracking Error Comparison")
    plt.grid(True)

    plt.legend(title="Policies")

    if out_dir is not None:
        plt.savefig(
            os.path.join(out_dir, "rmse_comparison.png"),
            dpi=300,
            bbox_inches="tight"
        )

    plt.figure(figsize=(10, 6))

    for agg, label, color in zip(aggregations, labels, colors):

        plt.plot(
            agg["rmse_mean"],
            agg["cot_mean"],
            marker="o",
            linewidth=2,
            color=color,
            label=label
        )

        for i, v in enumerate(agg["vel"][:-1]):

            plt.annotate(
                f"{v:.2f}",
                (agg["rmse_mean"][i], agg["cot_mean"][i]),
                fontsize=12,
                color="black",               # <--- Forza il testo in nero
                textcoords="offset points",  # <--- Specifica che l'offset è in punti tipografici
                xytext=(20, 8),               # <--- Sposta il testo di 0 punti a destra e 8 punti in alto
                ha="center",                 # <--- Centra il testo orizzontalmente sopra il punto
                va="bottom"                  # <--- Allinea il testo verticalmente
            )
    
    plt.ylim(bottom=0.3, top=0.4)
    plt.xlim(0.0, 0.15)
    plt.xlabel("Velocity RMSE")
    plt.ylabel("Cost of Transport (CoT)")
    plt.title("Efficiency vs Tracking Tradeoff")
    plt.grid(True)

    plt.legend(title="Policies")

    if out_dir is not None:
        plt.savefig(
            os.path.join(out_dir, "pareto_comparison.png"),
            dpi=300,
            bbox_inches="tight"
        )

    if show:
        plt.show()
    else:
        plt.close("all")


def main():

    benchmark_dirs = [

        #"/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2/baseline_plane/benchmark",

        #"/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_snn/baseline_snn/benchmark",

        # "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/rnd_baseline_0.00013/benchmark",
        # "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/rnd_baseline_0.00015/benchmark",
        # "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/rnd_baseline_0.00017/benchmark",
        # "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/rnd_baseline_0.00019/benchmark",

        # "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_snn/snn_spike_0.10/benchmark",
        # "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/rnd_spike_0.00015/benchmark",

        "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_snn/snn_spike_symm/benchmark",
        "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/rnd_spike_symm/benchmark",

        # "/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2/baseline_rough/benchmark",
        #"/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_snn/slopes_spike_symm/benchmark_small",
        #"/home/vittorio/Desktop/curiosity-based-snn-for-unitree_rl_gym/logs/rough_go2_rnd/rnd_slopes_spike_symm/benchmark_small",
 
    ]

    labels = [

        #"PPO",

        #"SNN",

        # "RND (0.00013)",
        # "RND (0.00015)",
        # "RND (0.00017)",
        # "RND (0.00019)",

        #"SPIKE (0.10)",
        #"RND SPIKE (0.10)",

        "SNN SPIKE SYMM",
        "RND SPIKE SYMM",

        #"SLOPE PPO",
        #"SNN SPIKE SYMM",
        #"RND SPIKE SYMM",


    ]

    df = create_reference_velocity_table(
    benchmark_dirs,
    labels,
    reference_velocity=1.0
    )

    print(df)

    compare_benchmarks(
        benchmark_dirs,
        labels=labels,
        out_dir=None,
        show=True
    )


if __name__ == "__main__":
    main()